Remove static functions
SRWieZ/thumbhash pull request #3
Opened 2023-03-26 22:04 UTC by jerrywham

## Removed
- helpers functions
- static functions

## Added
- Compatibility with PHP ^8.0
- Constructor
- Private properties
- Added getWith(), getHeight(), gethHash(), displayThumbhash()
- Moved extract_size_and_pixels_with_gd() and extract_size_and_pixels_with_imagick() from helpers to Thumbhash object

2023-03-29 13:47 UTC, mehdichaouch commented on composer.json
> +      "email": "srwiez@gmail.com",
Correct format for this node is:

```json
  "authors": [
    {
      "name": "Eser DENIZ",
      "email": "srwiez@gmail.com"
    },{
      "name": "Cyril MAGUIRE",
      "email": "github@ecyseo.net"
    }
]
```

2023-03-29 13:47 UTC, mehdichaouch commented on composer.json
> +  "name": "jerrywham/thumbhash",
This change will break the `composer require srwiez/thumbhash` command

2023-03-29 13:47 UTC, mehdichaouch commented on readme.md
> +composer require jerrywham/thumbhash
same as in composer

2023-04-04 10:56 UTC, SRWieZ requested changes
I'm not against a real object but I don't think this is the right way of doing it.
See my comments for further explanations.
Also, I second @mehdichaouch comments.

Thank you for your time but I won't merge this class as it is. 
Feel free to come with a different approach if you feel to.

Have a good day

2023-04-04 10:56 UTC, SRWieZ commented on src/Thumbhash.php
> +    private function extract_size_and_pixels_with_gd(string $content): array
Shouldn't be in this class. This code has nothing to do with thumbhash algorithm.

2023-04-04 10:56 UTC, SRWieZ commented on src/Thumbhash.php
> +    private function extract_size_and_pixels_with_imagick(string $content): array
Same here, nothing to do with thumbhash algorithm.

2023-04-04 10:56 UTC, SRWieZ commented on src/Thumbhash.php
> +    }
I'm not against a real object but this constructor is wrong for a few reasons

1. Lot of framework uses [Flysystem](https://flysystem.thephpleague.com/docs/ ) abstraction to interact with files across different filesystems. [Laravel](https://laravel.com/docs/10.x/filesystem) even add a layer on top of that. I can also go further, what if my file comes from a stream ? This library shouldn't be responsible of file processing.
2. Actually this class is "unidirectional", we can't take base64 hash and decode the image.

2023-05-10 14:56 UTC, closed without merging